#!/bin/sh

# cp Exercise directory
cp -r ~training/Exercises ~/

# install appropriate .bashrc
cp -b ~training/StudentSetup/.bashrc.mpi ~/.bashrc

# notify to reboot
echo "Boot Camp configured. Logout and login again."
