#!/bin/sh

# cp Exercise directory
cp -r ~training/Exercises ~/

# install appropriate .bashrc
cp -b ~training/StudentSetup/.bashrc.openacc ~/.bashrc

# notify to reboot
echo "OpenACC workshop configured. Logout and login again."
